#defaults:
#  - paths
#  - dataset: scannet
experiment:
  name: llm_${dataset.name}
  run: final
  port: "12340"
  batch_size: 2
  num_workers: 4

output_dir: ${paths.results}

align_corners: False
saliency: True
model_name: dense_clip
img_size: [320, 240]
patch_sizes: [256, 128, 64]
n_segments: 64
patch_w1: 1.0
patch_w2: 1.0
patch_w3: 1.0
strides: [2]
alpha: 0.5
beta: 0.01
mu: 0.1
is_sam: False
interpolate_logits: True
clip_model: laion/CLIP-ViT-B-32-laion2B-s34B-b79K
#sam_model: /storage3/TEV/gmei/weights/sam_vit_b_01ec64.pth
sam_model: /data/disk1/data/model_weights/sam_vit_b_01ec64.pth
